### ISSUE TITLE
KeyError: 'sum'

### ISSUE THREAD

**Issue by froggy974** [markcocker/influxdb-query-to-sensor#2]
hi ,

i'm trying to implement your nice script, but i'm struggling with error which i don't understant

here is my config below

````
service: pyscript.influxdb_query_to_entity
data:
  database: homeassistant
  query: >-
    SELECT mean("value") AS "mean_value" FROM "homeassistant"."autogen"."W" WHERE time > now() - 30d AND "entity_id"='shellyem_98cdac1f00a8_channel_1_power' GROUP BY time(1d) FILL(null)
  key_field_name: time
  value_field_name: sum
  entity_id: sensor.shellyem_chan1_30days
  unit_of_measurement: W
  friendly_name: Import
  icon: 'mdi:flash'
````

and the error message in log
````
exception in <apps.influxdb_query_to_entity.influxdb_query_to_entity> line 129: attributes[point[key_field_name]] = point[value_field_name] ^ KeyError: 'sum'
````

can you help me out to troubleshoot this error ?

**Comment by froggy974** [comment]
solved by removing `AS "mean_value" `

````
service: pyscript.influxdb_query_to_entity
data:
  database: homeassistant
  query: >-
    SELECT mean("value") FROM "homeassistant"."autogen"."kWh" WHERE time > now() - 720h AND "entity_id"='energy_total_usage_daily' GROUP BY time(1d) FILL(null)
  key_field_name: time
  value_field_name: mean
  entity_id: sensor.shellyem_chan1_influx
  unit_of_measurement: "W"
  friendly_name: "conso"
  icon: 'mdi:flash'

````
